[build]
  publish = "."
  command = "echo 'Build complete'"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[functions]
  directory = "functions"

[[plugins]]
  package = "netlify-plugin-python"

[build.processing]
  skip_processing = false