[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --bind :$PORT app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
PYTHON_VERSION = "3.9"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.9"